#!/usr/bin/env python3
"""
packreg - keep a modpack register in sync with a packwiz pack.

Machine-derived fields are regenerated on every sync.
Everything you write by hand is preserved untouched.

Usage:
    python packreg.py sync   [--pack DIR] [--register FILE]
    python packreg.py audit  [--pack DIR] [--register FILE]

sync   Rebuild the auto block for every mod. Adds blocks for new mods,
       flags mods that are in the register but no longer in the pack.
       Never touches your notes.

audit  Report which mods still have no notes, plus anything stale.
       Exits 1 if there is unfinished work, so it can gate a commit hook.
"""

import argparse
import re
import sys
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

AUTO_START = "<!-- packreg:auto -->"
AUTO_END = "<!-- /packreg:auto -->"
STALE_MARK = "> **STALE** - no longer present in the pack."

NOTE_FIELDS = [
    ("Purpose", "why this mod is in the pack"),
    ("Owns", "which system it is the authority for, or 'nothing'"),
    ("Config", "what you changed away from defaults"),
    ("Conflicts", "known overlaps and how they were resolved"),
]

HEADER = """# Pack register

One block per mod. The fenced auto section is regenerated by `packreg.py sync` -
do not hand-edit it. Everything outside those markers is yours and is preserved.

Fill in the notes when you add the mod, not later. If you cannot say why a mod
is here, that is the finding.
"""


@dataclass
class Mod:
    slug: str
    name: str
    filename: str = ""
    side: str = "both"
    source: str = "unknown"
    project_id: str = ""
    version_id: str = ""
    pinned: bool = False
    warnings: list = field(default_factory=list)


# ---------------------------------------------------------------- parsing

def parse_pack(pack_dir: Path) -> tuple[dict, list[Mod]]:
    """Read pack.toml and every *.pw.toml under the pack."""
    pack_meta = {}
    pack_toml = pack_dir / "pack.toml"
    if pack_toml.is_file():
        with pack_toml.open("rb") as fh:
            pack_meta = tomllib.load(fh)

    mods = []
    for path in sorted(pack_dir.rglob("*.pw.toml")):
        try:
            with path.open("rb") as fh:
                data = tomllib.load(fh)
        except tomllib.TOMLDecodeError as exc:
            print(f"  ! skipping {path.name}: {exc}", file=sys.stderr)
            continue
        mods.append(build_mod(path, data, pack_meta))
    return pack_meta, mods


def build_mod(path: Path, data: dict, pack_meta: dict) -> Mod:
    slug = path.name[: -len(".pw.toml")]
    mod = Mod(slug=slug, name=data.get("name", slug))
    mod.filename = data.get("filename", "")
    mod.side = data.get("side", "both")
    mod.pinned = bool(data.get("pin", False))

    update = data.get("update", {})
    if "modrinth" in update:
        mod.source = "modrinth"
        mod.project_id = str(update["modrinth"].get("mod-id", ""))
        mod.version_id = str(update["modrinth"].get("version", ""))
    elif "curseforge" in update:
        mod.source = "curseforge"
        mod.project_id = str(update["curseforge"].get("project-id", ""))
        mod.version_id = str(update["curseforge"].get("file-id", ""))
    elif data.get("download", {}).get("url"):
        mod.source = "direct url"

    check_filename(mod, pack_meta)
    return mod


def check_filename(mod: Mod, pack_meta: dict) -> None:
    """Cheap sanity checks against the jar filename. These are hints, not proof."""
    fname = mod.filename.lower()
    if not fname:
        mod.warnings.append("no filename recorded")
        return

    versions = pack_meta.get("versions", {})
    target_mc = str(versions.get("minecraft", ""))
    loaders = [k for k in versions if k in ("neoforge", "forge", "fabric", "quilt")]
    target_loader = loaders[0] if loaders else ""

    if target_mc:
        major_minor = ".".join(target_mc.split(".")[:2])
        found = re.findall(r"\d+\.\d+(?:\.\d+)?", mod.filename)
        mc_like = [v for v in found if v.startswith(major_minor)]
        if mc_like and target_mc not in mod.filename:
            mod.warnings.append(
                f"filename mentions {', '.join(sorted(set(mc_like)))} but pack targets {target_mc}"
            )

    if target_loader:
        others = {"forge", "fabric", "quilt", "neoforge"} - {target_loader}
        # 'neoforge' contains 'forge', so match on word-ish boundaries
        for other in sorted(others):
            if re.search(rf"(?<![a-z]){other}(?![a-z])", fname):
                if other == "forge" and "neoforge" in fname:
                    continue
                mod.warnings.append(f"filename mentions '{other}', pack targets '{target_loader}'")

    if "beta" in fname or "alpha" in fname:
        mod.warnings.append("pre-release build")


# ---------------------------------------------------------------- register

def split_blocks(text: str) -> tuple[str, dict[str, str]]:
    """Split the register into its preamble and a {slug: block_body} map."""
    parts = re.split(r"^## +(?=\S)", text, flags=re.MULTILINE)
    preamble = parts[0]
    blocks = {}
    for chunk in parts[1:]:
        line, _, rest = chunk.partition("\n")
        blocks[line.strip()] = rest
    return preamble, blocks


def auto_section(mod: Mod) -> str:
    rows = [
        f"- File: `{mod.filename or 'unknown'}`",
        f"- Source: {mod.source}"
        + (f" (`{mod.project_id}`)" if mod.project_id else ""),
        f"- Side: {mod.side}",
    ]
    if mod.version_id:
        rows.append(f"- Version id: `{mod.version_id}`")
    if mod.pinned:
        rows.append("- Pinned: yes")
    for warning in mod.warnings:
        rows.append(f"- CHECK: {warning}")
    return "\n".join([AUTO_START, *rows, AUTO_END])


def blank_notes() -> str:
    return "\n".join(f"**{label}:** <!-- {hint} -->" for label, hint in NOTE_FIELDS)


def replace_auto(body: str, new_auto: str) -> str:
    """Swap the auto section, leaving all hand-written text alone."""
    pattern = re.compile(
        re.escape(AUTO_START) + r".*?" + re.escape(AUTO_END), re.DOTALL
    )
    if pattern.search(body):
        return pattern.sub(lambda _: new_auto, body, count=1)
    return new_auto + "\n\n" + body.lstrip("\n")


def mark_stale(body: str) -> str:
    if STALE_MARK in body:
        return body
    return STALE_MARK + "\n\n" + body.lstrip("\n")


def unmark_stale(body: str) -> str:
    return body.replace(STALE_MARK + "\n\n", "").replace(STALE_MARK + "\n", "")


def render(preamble: str, order: list[str], blocks: dict[str, str]) -> str:
    out = [preamble.rstrip("\n"), ""]
    for slug in order:
        out.append(f"## {slug}")
        out.append(blocks[slug].strip("\n"))
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


# ---------------------------------------------------------------- commands

def cmd_sync(args) -> int:
    pack_dir = Path(args.pack)
    reg_path = Path(args.register)
    _, mods = parse_pack(pack_dir)
    if not mods:
        print(f"No .pw.toml files found under {pack_dir}", file=sys.stderr)
        return 1

    if reg_path.is_file():
        preamble, blocks = split_blocks(reg_path.read_text(encoding="utf-8"))
    else:
        preamble, blocks = HEADER, {}
    if not preamble.strip():
        preamble = HEADER

    added, updated = [], 0
    live = {m.slug for m in mods}

    for mod in mods:
        new_auto = auto_section(mod)
        if mod.slug in blocks:
            body = unmark_stale(blocks[mod.slug])
            merged = replace_auto(body, new_auto)
            if merged != blocks[mod.slug]:
                updated += 1
            blocks[mod.slug] = merged
        else:
            blocks[mod.slug] = new_auto + "\n\n" + blank_notes()
            added.append(mod.slug)

    stale = []
    for slug in blocks:
        if slug not in live:
            stale.append(slug)
            blocks[slug] = mark_stale(blocks[slug])

    order = sorted(live) + sorted(stale)
    reg_path.write_text(render(preamble, order, blocks), encoding="utf-8")

    print(f"{len(mods)} mods in pack -> {reg_path}")
    print(f"  added   {len(added)}" + (f": {', '.join(added[:6])}" if added else ""))
    print(f"  updated {updated}")
    if stale:
        print(f"  stale   {len(stale)}: {', '.join(stale)}")
    return 0


def cmd_audit(args) -> int:
    reg_path = Path(args.register)
    if not reg_path.is_file():
        print(f"No register at {reg_path}. Run sync first.", file=sys.stderr)
        return 1

    _, blocks = split_blocks(reg_path.read_text(encoding="utf-8"))
    unnoted, stale, flagged = [], [], []

    for slug, body in blocks.items():
        if STALE_MARK in body:
            stale.append(slug)
        if re.search(r"^\*\*Purpose:\*\*\s*(<!--.*?-->)?\s*$", body, re.MULTILINE):
            unnoted.append(slug)
        for line in re.findall(r"^- CHECK: (.+)$", body, re.MULTILINE):
            flagged.append((slug, line))

    print(f"{len(blocks)} mods in register\n")
    if flagged:
        print(f"Flagged by sync ({len(flagged)}):")
        for slug, note in flagged:
            print(f"  {slug}: {note}")
        print()
    if stale:
        print(f"In register but not in pack ({len(stale)}):")
        for slug in stale:
            print(f"  {slug}")
        print()
    if unnoted:
        print(f"No purpose written ({len(unnoted)}):")
        for slug in unnoted:
            print(f"  {slug}")
        print()

    if not (flagged or stale or unnoted):
        print("Clean.")
        return 0
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(prog="packreg", description=__doc__)
    sub = parser.add_subparsers(dest="cmd", required=True)
    for name, fn in (("sync", cmd_sync), ("audit", cmd_audit)):
        p = sub.add_parser(name)
        p.add_argument("--pack", default=".", help="packwiz pack root (default: .)")
        p.add_argument("--register", default="REGISTER.md", help="register file")
        p.set_defaults(func=fn)
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
