name = "Barren Skies Test Pack"
author = "Ryanath55"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec35c545d53b5aa22b2ee10a8bc277ae425dc8c472ca95eddaa483b37bf1f312"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
