name = "Peanut Flavored"
author = "Ryanath55"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0bafa359ea4571a352c4222ef519487c49cfff0f494d8709f160d65d6596c03"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
