name = "Barren Skies Test Pack"
author = "Ryanath55"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2e604f62aef3700e5a4a149f3324f33e6e00becb7f0bca2f19d048e7bb0c377"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
