version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
offroad = true
hybrid_aquatic = true
farmersdelight = true
tide = true
endersdelight = true
aeroencasedpipe = true
upgrade_aquatic = true
createbigcannons = true
incubation = true
woodworks = true
interiors = true
culturaldelights = true
endrem = true
create = true
oceansdelight = true
aeronautics = true
environmental = true
brewinandchewin = true
simulated = true
dungeonsdelight = true
clayworks = true
sable_player_ragdoll = true
cookielicious = true
minecraft = true
progressionreforged = true
copycats = true
atmospheric = true
dndecor = true
create_connected = true
rusticdelight = true
create_dragons_plus = true
autumnity = true
createdieselgenerators = true
ends_delight = true
createdeco = true
aeronautics_utility_objects = true
abnormals_delight = true
endermanoverhaul = true
bellsandwhistles = true
berry_good = true
sliceanddice = true
scorchful = true
buzzier_bees = true
mynethersdelight = true
moonlight = true
immersiveenchanting = true
aeroworks = true
neapolitan = true
