#!/usr/bin/env bash
# Regenerate mods/modlist.md from whatever is currently in mods/.
# Jars themselves are not tracked, so this manifest is the record of what the
# pack is. Run it after adding, removing, or toggling a mod, then commit.
set -euo pipefail
cd "$(dirname "$0")/.."

out=mods/modlist.md
{
  echo "# Mod list"
  echo
  echo "Generated by \`tools/update-modlist.sh\` on $(date +%Y-%m-%d)."
  echo "Jars are not tracked in git — re-download these exact versions to rebuild the pack."
  echo
  echo "## Active ($(ls mods/*.jar 2>/dev/null | wc -l))"
  echo
  for f in mods/*.jar; do
    [ -e "$f" ] || continue
    echo "- \`$(basename "$f")\`"
  done
  echo
  echo "## Disabled ($(ls mods/*.jar.disabled 2>/dev/null | wc -l))"
  echo
  for f in mods/*.jar.disabled; do
    [ -e "$f" ] || continue
    echo "- \`$(basename "$f" .disabled)\`"
  done
} > "$out"

echo "wrote $out"
